<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2012 NVIDIA Corporation.  All Rights Reserved.

     NVIDIA Corporation and its licensors retain all intellectual property and
     proprietary rights in and to this software and related documentation.  Any
     use, reproduction, disclosure or distribution of this software and related
     documentation without an express license agreement from NVIDIA Corporation
     is strictly prohibited.
 */
-->
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, voice-call)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT voice-call (pcm_config, device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl)>
  <!ELEMENT alsa_device EMPTY>
  <!ATTLIST alsa_device name (music|voice|aux|voice-call|bt-voice-call|compress_offload) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT alsa_device EMPTY>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ELEMENT pcm_config EMPTY>
  <!ELEMENT device EMPTY>
  <!ATTLIST device name (speaker|headphone|earpiece|bt-sco|aux|builtin-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call|compress_offload) #REQUIRED>
  <!ELEMENT device EMPTY>
  <!ELEMENT path EMPTY>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT path EMPTY>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT param EMPTY>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>
  <alsa_device name="music"
               card_id="-1"
               card_name="tegrart5645"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="ulp" val="0"/>
    <param name="compress_offload" val="0"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="nvoice" val="0"/>
    <param name="HW Rates" val="48000 44100"/>
    <param name="flags" val="AUDIO_OUTPUT_FLAG_PRIMARY"/>

    <path>
      <!--playback paths-->
      <ctl name="Speaker Playback Volume" val="0x19"/>
      <ctl name="Headphone Jack Switch" val="0"/>
      <ctl name="Int Spk Switch" val="0"/>
      <ctl name="Int Mic Switch" val="0"/>
      <ctl name="Mic Jack Switch" val="0"/>
      <ctl name="Codec VMixer Codec Switch" val="1"/>
    </path>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="ADC Capture Switch" val="1"/>
          <ctl name="STO1 ADC Boost Gain" val="3"/>
          <ctl name="RECMIXL BST2 Switch" val="1"/>
          <ctl name="RECMIXR BST2 Switch" val="1"/>
          <ctl name="RECMIXL BST1 Switch" val="0"/>
          <ctl name="RECMIXR BST1 Switch" val="0"/>
          <ctl name="Stereo1 ADC L1 Mux" val="ADC"/>
          <ctl name="Stereo1 ADC R1 Mux" val="ADC"/>
          <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="Sto1 ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="RECMIXL BST2 Switch" val="0"/>
          <ctl name="RECMIXR BST2 Switch" val="0"/>
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="ADC Capture Switch" val="1"/>
          <ctl name="STO1 ADC Boost Gain" val="1"/>
          <ctl name="RECMIXL BST2 Switch" val="0"/>
          <ctl name="RECMIXR BST2 Switch" val="0"/>
          <ctl name="RECMIXL BST1 Switch" val="1"/>
          <ctl name="RECMIXR BST1 Switch" val="1"/>
          <ctl name="Stereo1 ADC L1 Mux" val="ADC"/>
          <ctl name="Stereo1 ADC R1 Mux" val="ADC"/>
          <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="Sto1 ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="RECMIXL BST1 Switch" val="0"/>
          <ctl name="RECMIXR BST1 Switch" val="0"/>
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegrart5645"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name="voice-call"
               card_id="-1"
               card_name="tegrart5645"
               device_id="3">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <at node="/dev/ttyACM2" type="VOLUME" cmd="at+clvl="/>
      <at node="/dev/ttyACM2" type="IN_CALL" cmd="at%iapvc="/>

      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
          <at  node="/dev/ttyACM2" type="PROFILE" cmd="at%iaudcnf=1\r\n"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
          <at  node="/dev/ttyACM2" type="PROFILE" cmd="at%iaudcnf=2\r\n"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
    </call>

    <call>
      <pcm_config start_threshold="1"/>
      <at node="/dev/ttyACM2" type="MUTE" cmd="at+cmut="/>
      <at node="/dev/ttyACM2" type="MUTE" cmd="at+cmut="/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="ADC Capture Switch" val="1"/>
          <ctl name="STO1 ADC Boost Gain" val="3"/>
          <ctl name="RECMIXL BST2 Switch" val="1"/>
          <ctl name="RECMIXR BST2 Switch" val="1"/>
          <ctl name="RECMIXL BST1 Switch" val="0"/>
          <ctl name="RECMIXR BST1 Switch" val="0"/>
          <ctl name="Stereo1 ADC L1 Mux" val="ADC"/>
          <ctl name="Stereo1 ADC R1 Mux" val="ADC"/>
          <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="Sto1 ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="RECMIXL BST2 Switch" val="0"/>
          <ctl name="RECMIXR BST2 Switch" val="0"/>
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="ADC Capture Switch" val="1"/>
          <ctl name="STO1 ADC Boost Gain" val="1"/>
          <ctl name="RECMIXL BST2 Switch" val="0"/>
          <ctl name="RECMIXR BST2 Switch" val="0"/>
          <ctl name="RECMIXL BST1 Switch" val="1"/>
          <ctl name="RECMIXR BST1 Switch" val="1"/>
          <ctl name="Stereo1 ADC L1 Mux" val="ADC"/>
          <ctl name="Stereo1 ADC R1 Mux" val="ADC"/>
          <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="Sto1 ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="RECMIXL BST1 Switch" val="0"/>
          <ctl name="RECMIXR BST1 Switch" val="0"/>
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </call>
  </alsa_device>

  <alsa_device name="music"
               card_id="-1"
               card_name="tegrart5639"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="ulp" val="0"/>
    <param name="compress_offload" val="0"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="nvoice" val="0"/>
    <param name="HW Rates" val="48000 44100"/>
    <param name="flags" val="AUDIO_OUTPUT_FLAG_PRIMARY"/>

    <path>
      <!--playback paths-->
      <ctl name="Speaker Playback Volume" val="0x1f"/>
      <ctl name="ADC Capture Volume" val="0x57"/>
      <ctl name="Headphone Jack Switch" val="0"/>
      <ctl name="Int Spk Switch" val="0"/>
      <ctl name="Int Mic Switch" val="0"/>
      <ctl name="Mic Jack Switch" val="0"/>
      <ctl name="Codec VMixer Codec Switch" val="1"/>
    </path>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
          <ctl name="Speaker Playback Volume" val="0x19"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
          <ctl name="Speaker Playback Volume" val="0xf"/>
          <ctl name="SPK MIXR DAC R1 Switch" val="0"/>
        </path>
        <path name="off">
          <ctl name="SPK MIXR DAC R1 Switch" val="1"/>
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="Stereo ADC L2 Mux" val="DMIC1"/>
          <ctl name="Stereo ADC R2 Mux" val="DMIC1"/>
          <ctl name="Stereo ADC MIXL ADC1 Switch" val="0"/>
          <ctl name="Stereo ADC MIXR ADC1 Switch" val="0"/>
          <ctl name="Stereo ADC MIXL ADC2 Switch" val="1"/>
          <ctl name="Stereo ADC MIXR ADC2 Switch" val="1"/>
          <ctl name="DMIC Switch" val="DMIC1"/>
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Stereo ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="Stereo ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="ADC Capture Switch" val="1"/>
          <ctl name="RECMIXL BST1 Switch" val="0"/>
          <ctl name="RECMIXR BST1 Switch" val="0"/>
          <ctl name="RECMIXL BST2 Switch" val="1"/>
          <ctl name="RECMIXR BST2 Switch" val="1"/>
          <ctl name="Stereo ADC L1 Mux" val="ADC"/>
          <ctl name="Stereo ADC R1 Mux" val="ADC"/>
          <ctl name="Stereo ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Stereo ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="Stereo ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="Stereo ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="IN1 Mode Control" val="Differential"/>
          <ctl name="IN2 Mode Control" val="Differential"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="RECMIXL BST2 Switch" val="0"/>
          <ctl name="RECMIXR BST2 Switch" val="0"/>
          <ctl name="Stereo ADC MIXL ADC1 Switch" val="0"/>
          <ctl name="Stereo ADC MIXR ADC1 Switch" val="0"/>
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegrart5639"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name="voice-call"
               card_id="-1"
               card_name="tegrart5639"
               device_id="3">
    <pcm_config rate="16000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <call>
      <ctl name="Speaker Playback Volume" val="0x19"/>
      <ctl name="ADC Capture Volume" val="0x57"/>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <at node="/dev/ttyACM2" type="VOLUME" cmd="at+clvl="/>
      <at node="/dev/ttyACM2" type="IN_CALL" cmd="at%iapvc="/>

      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
          <ctl name="Speaker Playback Volume" val="0x19"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <at  node="/dev/ttyACM2" type="PROFILE" cmd="at%iaudcnf=0\r\n"/>
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
          <ctl name="Speaker Playback Volume" val="0xf"/>
          <ctl name="SPK MIXR DAC R1 Switch" val="0"/>
        </path>
        <path name="off">
          <ctl name="SPK MIXR DAC R1 Switch" val="1"/>
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
    </call>
    <call>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="Stereo ADC L2 Mux" val="DMIC1"/>
          <ctl name="Stereo ADC R2 Mux" val="DMIC1"/>
          <ctl name="Stereo ADC MIXL ADC1 Switch" val="0"/>
          <ctl name="Stereo ADC MIXR ADC1 Switch" val="0"/>
          <ctl name="Stereo ADC MIXL ADC2 Switch" val="1"/>
          <ctl name="Stereo ADC MIXR ADC2 Switch" val="1"/>
          <ctl name="DMIC Switch" val="DMIC1"/>
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Stereo ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="Stereo ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="ADC Capture Switch" val="1"/>
          <ctl name="RECMIXL BST1 Switch" val="0"/>
          <ctl name="RECMIXR BST1 Switch" val="0"/>
          <ctl name="RECMIXL BST2 Switch" val="1"/>
          <ctl name="RECMIXR BST2 Switch" val="1"/>
          <ctl name="Stereo ADC L1 Mux" val="ADC"/>
          <ctl name="Stereo ADC R1 Mux" val="ADC"/>
          <ctl name="Stereo ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Stereo ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="Stereo ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="Stereo ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="IN1 Mode Control" val="Differential"/>
          <ctl name="IN2 Mode Control" val="Differential"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="RECMIXL BST2 Switch" val="0"/>
          <ctl name="RECMIXR BST2 Switch" val="0"/>
          <ctl name="Stereo ADC MIXL ADC1 Switch" val="0"/>
          <ctl name="Stereo ADC MIXR ADC1 Switch" val="0"/>
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </call>
  </alsa_device>

  <alsa_device name ="bt-voice-call"
           card_id="-1"
           card_name="tegrart5639"
           device_id="4">
    <pcm_config rate="8000"
            channels="1"
            bps="16"
            period_size="256"
            period_count="4"
            start_threshold="1023"
            stop_threshold="1024"
            silence_threshold="0"
            avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <device name="bt-sco"/>
    </call>
    <call>
      <device name="bt-sco-mic"/>
    </call>
  </alsa_device>

  <alsa_device name ="aux"
             card_id="-1"
             card_name="Tegra"
             device_id="3">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="HW Rates" val="48000 44100"/>
    <playback>
      <device name="aux"/>
    </playback>
  </alsa_device>

  <alsa_device name="wfd">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"/>
    <playback>
      <device name="wfd"/>
    </playback>
  </alsa_device>
</AudioConfigs>
